#!/bin/bash

# To find your disply name:  
# xrandr | grep " connected" | cut -f1 -d " "
# replace below all  <DP-2>  with your actual display name

while :
do
    clear
    cat<<EOF
    
	Set Screen Brightness

            1 
            2
            3
            4
            5
            6   
            7
            8

            0 to exit

EOF

read -n1 -s
    case "$REPLY" in
    "1")  xrandr --output DP-2 --brightness .3;;
    "2")  xrandr --output DP-2 --brightness .4;;
    "3")  xrandr --output DP-2 --brightness .5;;
    "4")  xrandr --output DP-2 --brightness .6;;
    "5")  xrandr --output DP-2 --brightness .7;;
    "6")  xrandr --output DP-2 --brightness .8;;
    "7")  xrandr --output DP-2 --brightness .9;;
    "8")  xrandr --output DP-2 --brightness 1.0;;
    "0")  exit;;

    esac
    sleep .05
done
